export const projects = [
  {
    img: "/projects imgs/movimania.jpg",
    name: "MovieMania",
    description: "MovieMania Website",
    link: "https://moviemania-mohamedtahar.netlify.app/",
    category: "Websites",
  },
  {
    img: "/projects imgs/omnifood.jpg",
    name: "Omnifood",
    description: "Restaurant Landing Page",
    link: "https://omnifood-mohamed-tahar.netlify.app/",
    category: "Landing Pages",
  },
  {
    img: "/projects imgs/metaversus.jpg",
    name: "MetaVersus",
    description: "MetaVersus Landing Page",
    link: "https://metaversus-mohamedtahar.netlify.app/",
    category: "Landing Pages",
  },
  {
    img: "/projects imgs/hoobank.jpg",
    name: "Hoobank",
    description: "Hoobank Landing Page",
    link: "https://hoobank-mohamedtahar.netlify.app/",
    category: "Landing Pages",
  },
  {
    img: "/projects imgs/shopit.jpg",
    name: "ShopIt",
    description: "Ecommerce Website",
    link: "https://shopit-mohamedtahar.netlify.app/",
    category: "Ecommerce Websites",
  },
  {
    img: "/projects imgs/dataware.jpg",
    name: "DataWarehouse",
    description: "DataWarehouse Landing Page",
    link: "https://datawarehouse-mohamedtahar.netlify.app/",
    category: "Landing Pages",
  },
  {
    img: "/projects imgs/uniconfort-1.png",
    name: "Uniconfort",
    description: "Uniconfort Ecommerce Store",
    link: "https://uniconfortmeuble.store",
    category: "Ecommerce Websites",
  },
];
